# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ languageJava ? (import ../language-java {}), haskellPackages ? (import <nixpkgs> {}).haskellPackages }:
let
  inherit (haskellPackages) cabal lens parsec prettyShow tagged;
in cabal.mkDerivation (self: {
  pname = "syntack";
  version = "0.1.0.0";
  src = ./.;
  isLibrary = false;
  isExecutable = true;
  buildDepends = [ languageJava lens parsec prettyShow tagged ];
  meta = {
    license = self.stdenv.lib.licenses.unfree;
    platforms = self.ghc.meta.platforms;
  };
})
